---
baseURL: https://apprentismarket.netlify.app/
languageCode: fr-fr
title: Les apprentis marketeux
module:
  imports:
  - path: github.com/theNewDynamic/gohugo-theme-ananke
DefaultContentLanguage: fr
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  site_logo: /images/logo.png
  description: test
  facebook: https://www.facebook.com/profile.php?id=100042726557510
  twitter: https://twitter.com/TaillandierAnn1
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: https://www.linkedin.com/in/anne-taillandier/
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-lightest-blue
  featured_image: "/images/Marketing.jpg"
  recent_posts_number: 2
